sudo: required
services:
  - docker
language: node_js
node_js:
  - '8'
addons:
  apt:
    packages: rpm
notifications:
  slack:
    rooms:
      secure: mqHrQAw8feDH8e8+/gV8C1dbeC3e3tkS/AGx9XTtUoCVbY45C0X6KRYaSpK9H1WNjY7AjBnrEjsvQlivhXKIp41FQBhnief1t+0zGtnkwtQiRumWOyoo2uN+BNVE+fE8W0QyasL/SjarBFAqJkbQPH5EiRxcil8Wcuk2mE44a3kRL+sE67rPqjXSvc5t3N5kupziIMW90dxpeV584t3CS5VfPbrwLdrmZtDOgZj6ijsmM41N6+KXl+44LKK0bXApGD4WWX7iESivzjM+mOTVUhO7o17vpQ7JwG3EXymVRxUnIyANWI0KYzQGNwWEl1XWBrkw4/oGW/xOJK9nsW2EkoBnUjERk9xYPzte4RQO2IpnLrBLCWG0HL4NBKfbftJLtUxQFXhzIQ7MqYjwCKrSSK23eNl/qLl+8VkaNBa0hutGBPWYG2KF/SOMu3rPDGGzT+LD/atbAnm/m6M3p2XkR7vHHUgfwZ10vt2HLvpElK6ScT0OhZ1wNtfRnms7HJO44rp4bZMyJURU6wkEMeNoOOrfSVGIkwbXAJja2EGFVBcIeOTJpQBBxWnRCyEC2BmxX2rjuiBibGke7VpmSOUadlQxG7DotspfqzNy93VulI3GnwkZr3PqwBp8/Ce4v68uk/WdOx2Y5ug98CoBqF17XpM2I21wSJxAKu5B1zRgL5I=
    on_success: never
    on_failure: always
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
install:
  - make lint
before_script:
  - gem install fpm
script:
  - make packages
before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
deploy:
  - provider: releases
    api_key:
      secure: dQNDfnfgQdm9fYPYQtqpgkRt8jWZ8pT9qWWCaC74nzubjDgqwxU/1w/tbyt5AoPplthWTRooxt45lJ7VbMbTxLT9iwdhnHsh3BxpaadZdDD11D+nKWjpugUmOAM6SZolCr0dQOW1TK8lRYBiRMe1baosnhM2NbpJ6RGibAal6w9vxbo35fXBjNa9BoRTeK0ehUW1E4PWQ73qtzKzgdei2bKRElbd5EpWpe4xbm1tOcJTxEClWnBD7L8//g/aj+rH4g0xjdfN521t93A4rCOwTYyH69/J115xqoyz5UChN16hs/qQ7BcgtQlFkWs/vbQ1qAdL3JF916buyjAXNHxPG2aYE4UtaKTQJRwRNSWC14puqZG5IGwiyOFJRqMKOi0BMoF2b9IIi8GPgYZ96fLGU3oDc9jO4J4qrenpdg1ZENF0ljMb4QRB6Xr7F6juA72taHKvpbb1uRJMpG2i+DC4m5XGRV2HonYeKwrjmT/HaWC8cRE9ajq2B972vXKw1b1QqQAxhbpVP7NbCZSXMO7yN5Ltq0zz+Onw3yeTSFNLIPf8PgislfXyET+iqVUr5LNupgoj2PqCgBvo9QuQVqDcZXKiVsUIAuUJkVCrKQ5fxZfZUi7cWKRsdpFfC7SIZPlccwtaYrLdlwvZLISfiHwQcD2gCye6IdlTIbU6Rknuf44=
    file_glob: true
    file:
      - build/moira*.tar.gz
      - build/moira*.rpm
      - build/moira*.deb
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script:
      - make docker_feature_image GIT_BRANCH="${TRAVIS_BRANCH////-}"
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH =~ ^(feature|hotfix).*$
  - provider: script
    script:
      - make docker_develop_image
    skip_cleanup: true
    on:
      branch: develop
  - provider: script
    script:
      - make docker_release_image
    skip_cleanup: true
    on:
      tags: true
