sudo: required
services:
  - docker
language: node_js
node_js:
  - '6'
  - '8'
addons:
  apt:
    packages: rpm
install:
  - make prepare
before_script:
  - gem install fpm
script:
  - make build

before_deploy:
  - export RELEASE_PKG_TAR=$(ls build/moira*.tar.gz)
  - export RELEASE_PKG_RPM=$(ls build/moira*.rpm)
  - export RELEASE_PKG_DEB=$(ls build/moira*.deb)
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
deploy:
  - provider: script
    script: make docker_push
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: make docker_push_release
    skip_cleanup: true
    on:
      branch: master
